version: "3.7"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
    - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  postgres_temp:
    image: postgres:13
    restart: always
    ports:
      - 5432:5200
    env_file:
    - .env.temp
    volumes:
      - ./postgres-data-2:/var/lib/postgresql/data

  postgres_testing:
    image: postgres:13
    container_name: postgres_testing
    restart: always
    ports:
      - 5444:5432
    env_file:
      - .env.test

volumes:
  postgres-data: