import * as z from 'zod'
import { EmployeeStatus, EmployeeRole } from '@prisma/client'

export const EmployeeModel = z.object({
  id: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  status: z.nativeEnum(EmployeeStatus),
  roles: z.nativeEnum(EmployeeRole).array(),
  salary: z.number().nullish(),
  acceptedPrivacyPolicy: z.boolean(),
  acceptedTermsOfService: z.boolean(),
  salaryFiat: z.number().nullish(),
  advanceMaxAmount: z.number(),
  advanceAvailableAmount: z.number(),
  currencyId: z.number().int().nullish(),
  documentIssueDate: z.date().nullish(),
  birthDay: z.date().nullish(),
  salaryCrypto: z.number().nullish(),
  advanceCryptoMaxAmount: z.number().nullish(),
  advanceCryptoAvailableAmount: z.number().nullish(),
  cryptocurrencyId: z.number().int().nullish(),
  walletId: z.string().nullish(),
  numberOfChildren: z.number().int(),
  phone: z.string().nullish(),
  address: z.string().nullish(),
  companyId: z.string(),
  userId: z.string(),
  bankAccountId: z.string().nullish(),
  genderId: z.number().int().nullish(),
  jobDepartmentId: z.number().int().nullish(),
  jobPositionId: z.number().int().nullish(),
  countryId: z.number().int().nullish(),
  stateId: z.number().int().nullish(),
  cityId: z.number().int().nullish(),
})
